### ISSUE TITLE
Error on the paper api dependency

### ISSUE THREAD

**Issue by Mouah1er** [Iltotore/ManaDrop#10]
Hi, the "url" of the paper api dependency is not `"com.destroystokyo.paper:paper-api:" + version + "-R0.1-SNAPSHOT"` in the latest versions, can you fix this? The new "url" is `"io.papermc.paper:paper-api:" + version + "-R0.1-SNAPSHOT"`.
Thanks

**Comment by Iltotore** [comment]
Hello. Is the new group `io.papermc.paper` available for all versions or only recent ones ?

**Comment by Mouah1er** [comment]
The io.papermc.paper is available for versions 1.17 to 1.18.2, and the com.destroystokyo.paper is available from version 1.9.4 to 1.16.5

**Comment by Iltotore** [comment]
Ok. I will fix that as soon as possible. Probably today or the coming week.

**Comment by Iltotore** [comment]
Closed by [5f36c96](https://github.com/Iltotore/ManaDrop/commit/5f36c96951dec998f99533e05bf2717fc42afd0a). A `0.4.2` will be published (the process can take up to a day).
