### ISSUE TITLE
Fix Wiki

### ISSUE THREAD

**Issue by PhoenixmitX** [Iltotore/ManaDrop#13]
in [attributes](https://github.com/Iltotore/ManaDrop/wiki/Spigot#attributes) are two typos

softDepend is softdepend
loadBefore is loadbefore

**Comment by Iltotore** [comment]
This is not a typo. The methods in ManaDrop are effectively `softDepend` and `loadBefore`. They are both correctly serialised to `softdepend` and `loadbefore` in the plugin.yml.

Feel free to reopen the issue if I missed something.

**Comment by PhoenixmitX** [comment]
thats correct but in the wiki there are only the lower case variants 

you cold mention it like you did it with

- name (`named`)
- prefix (`prefixed`)

to be 

- softdepend (`softDepend`)
- loadbefore (`loadBefore`)

when i read this i first thought that these methods are broken

**Comment by Iltotore** [comment]
Solved.
