### ISSUE TITLE
Spigot api version wrong syntax

### ISSUE THREAD

**Issue by Alessevan** [Iltotore/ManaDrop#3]
Hello, in the version 0.4-SNAPSHOT (I haven't test in the preview versions), when the plugin is built, the plugin.yml is correctly created except for api version. The syntax found in the plugin.yml, it's apiVersion instance of api-version. That's a problem because, the  legacy material.

![image](https://user-images.githubusercontent.com/44125445/85122201-76366880-b226-11ea-998b-2f5aa82ce30d.png)
![image](https://user-images.githubusercontent.com/44125445/85122266-91a17380-b226-11ea-99f2-00fa1d809700.png)
![image](https://user-images.githubusercontent.com/44125445/85122317-a4b44380-b226-11ea-95a9-3f5ad4752b5e.png)

**Comment by Iltotore** [comment]
You're right. This is a bug. I will fix it today. (based on CEST cycle.)

**Comment by Iltotore** [comment]
The bug has been fixed and the new plugin version ~~will be~~ is now pushed as `0.4.1-SNAPSHOT`. Next time, please paste your code instead of send a screen. 😉 

EDIT: You don't need to use `version project.version` because this is the default version value. You can remove this line.
