### ISSUE TITLE
Wiki repository example seems outdated

### ISSUE THREAD

**Issue by Allu2** [Iltotore/ManaDrop#4]
Wiki has an example with
```
repositories {
    spigotRepository() //https://hub.spigotmc.org/nexus/content/repositories/snapshots/
    sonatypeRepository() //https://oss.sonatype.org/content/repositories/snapshots
}
```

but when trying to use that IDE (IntellJ) doesn't seem to find the `spigotRepository()`, `sonatypeRepository()`,
even with the suggested imports

```
import static fr.il_totore.manadrop.MinecraftDependencyHelper.*
import static fr.il_totore.manadrop.MinecraftRepositoryHelper.*
```

switching the terms  `spigotRepository() -> spigotSnapshot()`, `sonatypeRepository() -> sonatype()` seems to fix the issue 🤔

Perhaps I'm missing something, or examples are out of date 😅

**Comment by Iltotore** [comment]
You're right. I will update it tomorrow.

Feel free to reopen this issue if needed.

PS: Sorry for waiting 4 days to reply but I'm actually on vacation ^^
