### ISSUE TITLE
Wiki methods outdated

### ISSUE THREAD

**Issue by Kyu** [Iltotore/ManaDrop#8]
In: https://github.com/Iltotore/ManaDrop/wiki/General-features#dependency-and-repository-shortcuts  

`spigotRepository()` should be `spigotSnapshot()`
`sonatypeRepository()` should be `sonatype()`

**Comment by Kyu** [comment]
It seems this was supposed to be resolved by #4 but it was closed

**Comment by Iltotore** [comment]
Hello,
you're right. I forgot to update this part of the documentation when I renamed these methods. I'm going to fix it.

**Comment by Iltotore** [comment]
Done. Thank you for reporting this !
